# Generated by Django 5.2.1 on 2025-06-12 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspeccionCerca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='repacionCerca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('materiales', models.CharField()),
                ('logo', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('cerca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspeccionCerca.inspeccioncerca')),
            ],
        ),
    ]
