# Generated by Django 5.2.1 on 2025-06-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repacionCerca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repacioncerca',
            old_name='fecha',
            new_name='fecha1',
        ),
        migrations.RenameField(
            model_name='repacioncerca',
            old_name='logo',
            new_name='logo1',
        ),
    ]
