# Generated by Django 5.2.1 on 2025-06-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repacionCerca', '0002_rename_fecha_repacioncerca_fecha1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repacioncerca',
            name='logo1',
            field=models.FileField(blank=True, null=True, upload_to='cargos'),
        ),
    ]
