# Generated by Django 5.2.1 on 2025-06-13 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repacionCerca', '0003_alter_repacioncerca_logo1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repacioncerca',
            old_name='fecha1',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='repacioncerca',
            old_name='logo1',
            new_name='logo',
        ),
    ]
