# Generated by Django 5.2.1 on 2025-06-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zonaSeguridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipoCerca', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
                ('logo', models.FileField(blank=True, null=True, upload_to='cargos')),
            ],
        ),
    ]
